FROM crystallang/crystal:1.0.0-alpine AS builder

RUN apk add --no-cache curl sqlite-static yaml-static git

RUN git clone https://github.com/iv-org/invidious.git /invidious

WORKDIR /invidious

RUN shards install && \
    curl -Lo ./lib/lsquic/src/lsquic/ext/liblsquic.a https://github.com/iv-org/lsquic-static-alpine/releases/download/v2.18.1/liblsquic.a

RUN crystal build ./src/invidious.cr \
    --static --warnings all \
    --link-flags "-lxml2 -llzma" \
    --cross-compile --target armv7-unknown-linux-gnueabihf --threads $(nproc) \
    --progress --stats --time 
