FROM alpine:3.13

RUN apk add --no-cache make llvm-dev llvm g++ git \
    gc-dev pcre-dev zlib-static zlib-dev libxml2 libxml2-dev \
    libssl1.1 sqlite-static yaml-static openssl-libs-static libevent-static

WORKDIR /root

RUN git clone https://github.com/crystal-lang/crystal 

RUN cd crystal && git checkout 1.0.0 && make deps

RUN mkdir -p /usr/share/crystal /usr/lib/crystal/bin 

RUN cp -R /root/crystal/src /usr/share/crystal/src

COPY --from=invidious:compile /invidious/invidious.o /root/invidious.o
COPY --from=invidious:lsquicBuilder /dist/liblsquic.a /root/liblsquic.a

RUN cc invidious.o -o invidious \
    -lxml2 -llzma -rdynamic -static \
    #-L/usr/bin/../lib/crystal/lib\
    -L/usr/share/crystal/src/lib \
    #/invidious/lib/lsquic/src/lsquic/ext/liblsquic.a \
    /root/liblsquic.a \
    -lyaml  -lxml2 -L/lib -lz -llzma -lm  -lsqlite3 -lz \
    -lssl -lcrypto \
    #`command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` \
    #`command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` \
    -lpcre -lm -lgc -lpthread \
    #/usr/share/crystal/src/ext/libcrystal.a \
    /root/crystal/src/ext/libcrystal.a \
    -levent -lrt -ldl \
    -L/usr/lib -L/usr/local/lib
